/*
 * This is common header for command line interface parser
 * generated by docopt.c utility.
 */

#ifndef __CMD_H__
#define __CMD_H__

struct cli {
	char *a;
	char *b;
	char *x;
	char *e;
	char *n;
	unsigned gcd;
	unsigned phi;
	unsigned v;
	unsigned verbose;
	unsigned h;
	unsigned help;
	unsigned version;
};

static const char * const cli_usage =
	"privatecalc.\n"
	"\n"
	"Usage:\n"
	"  privatecalc gcd <a> <b>\n"
	"  privatecalc phi [-v|--verbose] <x>\n"
	"  privatecalc [-v|--verbose] <e> <n>\n"
	"  privatecalc [-h|--help]\n"
	"  privatecalc --version\n"
	"\n"
	"Options:\n"
	"  -h --help     Show this screen.\n"
	"  --version     Show version.\n"
	"  -v --verbose  Be verbose\n"
	"\n";

int cli_parse(int argc, char **argv, struct cli *cli);
void cli_free(struct cli *cli);

#endif /* __CMD_H__ */
